DECLARE
	@NRO_IMPRESO AS VARCHAR(10)= '0011198067',
	@TIPO_DOCUMENTO AS VARCHAR(3)= 'FCV',
	@CODIGO_POR AS VARCHAR(20) = '21358000336'
BEGIN
	SET NOCOUNT ON
	Set Xact_Abort On
			
	DECLARE @NRO_INTERNO	AS INTEGER
	DECLARE @ID_DOCUMENTO	AS UNIQUEIDENTIFIER
	DECLARE @CHANNEL		AS VARCHAR(2)
	DECLARE @TIENDA			AS VARCHAR(3)
	DECLARE @NRO_CONTRATO	AS VARCHAR(10)
	DECLARE @NRO_DOCUMENTO	AS VARCHAR(20)
	DECLARE @DOCUMENTO		AS INTEGER

	--CREACIÓN DE TABLAS TEMPORALES
	CREATE TABLE #CODIGO_POR_DES(CHANNEL VARCHAR(2), TIENDA VARCHAR(3), NRO_CONTRATO VARCHAR(6), FECHA VARCHAR(10), CAJA VARCHAR(1), CORRELATIVO VARCHAR(10))
	CREATE TABLE #RESULT_ONE (TIPO_DOCUMENTO VARCHAR(1), NRO_IMPRESO VARCHAR(10), TOTAL INT)
	CREATE TABLE #RESULT_TWO (NRO_LINEA INT, COD_RAPIDO INT, DESCRIPCION VARCHAR(MAX), CANTIDAD VARCHAR(MAX), UNIDAD VARCHAR(10), TIPO_MONEDA VARCHAR(3), TOTAL INT)
	CREATE TABLE #RESULT_THREE (TIPO_DOCUMENTO_PAGO VARCHAR(10), MONTO INT)
	CREATE TABLE #RESULT_FOUR(ORDEN_VENTA VARCHAR(20), NRO_DOCUMENTO VARCHAR(20), CHANNEL VARCHAR(2), TIENDA VARCHAR(3), NRO_CONTRATO VARCHAR(6))

	IF @TIPO_DOCUMENTO = 'BLV'
	BEGIN
		--INSERT A TABLA TEMPORAL #CODIGO_POR_DES
		INSERT INTO #CODIGO_POR_DES(CHANNEL, TIENDA, NRO_CONTRATO, FECHA, CAJA, CORRELATIVO)
		SELECT 
			SUBSTRING(@CODIGO_POR,1,2),
			SUBSTRING(@CODIGO_POR,3,3),
			SUBSTRING(@CODIGO_POR,6,10),
			CONVERT(varchar,A.Fecha_Emision,112) as [YYYYMMDD],
			1,
			SUBSTRING(@NRO_IMPRESO,3,10)
			FROM SAV_VT.DBO.SAV_VT_BLVCab A WITH(NOLOCK)
				WHERE Nro_Impreso = @NRO_IMPRESO

		--HACEMOS SET A LA VARIABLE @DOCUMENTO Y @NRO_INTERNO
		SET @DOCUMENTO = 1
		SET @NRO_INTERNO =(SELECT Nro_Interno
							FROM SAV_VT.DBO.SAV_VT_BLVCab WITH(NOLOCK)
								WHERE Nro_Impreso = @NRO_IMPRESO)

		--INSERT A TABLA TEMPORAL #RESULT_ONE
		INSERT INTO #RESULT_ONE (TIPO_DOCUMENTO,NRO_IMPRESO,TOTAL)
			SELECT 
				CAST(Ltrim(Rtrim(@DOCUMENTO)) AS NVARCHAR) AS TIPO_DOCUEMNTO,
				CAST(Ltrim(Rtrim(@NRO_IMPRESO)) AS NVARCHAR) AS NRO_IMPRESO,
				Total FROM SAV_VT.DBO.SAV_VT_BLVCAB WITH(NOLOCK) WHERE Nro_Interno = @NRO_INTERNO 

		--INSERT A TABLA TEMPORAL #RESULT_TWO
		INSERT INTO #RESULT_TWO
			SELECT 
				CAST(Ltrim(Rtrim(Nro_Linea))	AS NVARCHAR) AS NRO_LINEA,
				CAST(Ltrim(Rtrim(Cod_Rapido))	AS NVARCHAR) AS COD_RAPIDO,
				CAST(Ltrim(Rtrim(Descripcion))	AS NVARCHAR) AS DESCRIPCION,
				CAST(Ltrim(Rtrim(Cantidad))		AS NVARCHAR) AS CANTIDAD,
				CAST(Ltrim(Rtrim(Cod_Unimed))	AS NVARCHAR) AS UNIDAD,
				CAST(Ltrim(Rtrim('CLP'))		AS NVARCHAR) AS TIPO_MONEDA,
				CAST(Ltrim(Rtrim(Total))		AS NVARCHAR) AS TOTAL
					FROM SAV_VT.DBO.SAV_VT_BLVDET WITH(NOLOCK)
						WHERE NRO_INTERNO = @NRO_INTERNO

		--HACEMOS SET A LA VARIABLE @ID_DOCUMENTO
		SET @ID_DOCUMENTO =(SELECT Id_Documento
								FROM SAV_VT.DBO.SAV_VT_BLVCab WITH(NOLOCK)
									WHERE Nro_Impreso = @NRO_IMPRESO)

		--INSERT A TABLA TEMPORAL ##RESULT_THREE
			INSERT INTO #RESULT_THREE
				SELECT 
					CAST(Ltrim(Rtrim(Tipo_DocumentoPago))	AS NVARCHAR) AS TIPO_DOCUMENTO_PAGO,
					CAST(Ltrim(Rtrim(Monto))				AS NVARCHAR) AS MONTO 
						FROM SAV_CJ.DBO.SAV_CJ_ASIGNACION_TRANSACCION WITH(NOLOCK)
							WHERE Id_DocumentoPagar = @ID_DOCUMENTO

		--HACEMOS SET A LA VARIABLE @NRO_DOCUMENTO, @CHANNEL, @TIENDA, @NRO_CONTRATO
		SET @NRO_DOCUMENTO = (SELECT FECHA + TIENDA + CAJA + CORRELATIVO FROM #CODIGO_POR_DES)
		SET @CHANNEL = (SELECT CHANNEL FROM #CODIGO_POR_DES)
		SET @TIENDA = (SELECT TIENDA FROM #CODIGO_POR_DES)
		SET @NRO_CONTRATO = (SELECT NRO_CONTRATO FROM #CODIGO_POR_DES)

		--INSERT A TABLA TEMPORAL #RESULT_THREE
		INSERT INTO #RESULT_FOUR(ORDEN_VENTA, NRO_DOCUMENTO, CHANNEL, TIENDA, NRO_CONTRATO)
				SELECT
					CAST(Ltrim(Rtrim(@CODIGO_POR))	AS NVARCHAR),
					CAST(Ltrim(Rtrim(@NRO_DOCUMENTO)) AS NVARCHAR),
					CAST(Ltrim(Rtrim(@CHANNEL)) AS NVARCHAR),
					CAST(Ltrim(Rtrim(@TIENDA)) AS NVARCHAR),
					CAST(Ltrim(Rtrim(@NRO_CONTRATO)) AS NVARCHAR)
	END

	IF @TIPO_DOCUMENTO = 'FCV'
	BEGIN
		--INSERT A TABLA TEMPORAL #CODIGO_POR_DES
		INSERT INTO #CODIGO_POR_DES(CHANNEL, TIENDA, NRO_CONTRATO, FECHA, CAJA, CORRELATIVO)
		SELECT 
			SUBSTRING(@CODIGO_POR,1,2),
			SUBSTRING(@CODIGO_POR,3,3),
			SUBSTRING(@CODIGO_POR,6,10),
			CONVERT(varchar,A.Fecha_Emision,112) as [YYYYMMDD],
			1,
			SUBSTRING(@NRO_IMPRESO,3,10)
			FROM SAV_VT.DBO.SAV_VT_FCVCab A WITH(NOLOCK)
				WHERE Nro_Impreso = @NRO_IMPRESO

		--HACEMOS SET A LA VARIABLE @DOCUMENTO, @NRO_INTERNO
		SET @DOCUMENTO = 2
		SET @NRO_INTERNO =(SELECT Nro_Interno
							FROM SAV_VT.DBO.SAV_VT_FCVCab WITH(NOLOCK)
								WHERE Nro_Impreso = @NRO_IMPRESO)

		--INSERT A TABLA TEMPORAL #RESULT_ONE
		INSERT INTO #RESULT_ONE (TIPO_DOCUMENTO,NRO_IMPRESO,TOTAL)
			SELECT 
				CAST(Ltrim(Rtrim(@DOCUMENTO)) AS NVARCHAR) AS TIPO_DOCUEMNTO,
				CAST(Ltrim(Rtrim(@NRO_IMPRESO)) AS NVARCHAR) AS NRO_IMPRESO,
				Total FROM SAV_VT.DBO.SAV_VT_FCVCab WITH(NOLOCK) WHERE Nro_Interno = @NRO_INTERNO 

		--INSERT A TABLA TEMPORAL #RESULT_TWO
		INSERT INTO #RESULT_TWO
			SELECT 
				CAST(Ltrim(Rtrim(Nro_Linea))	AS NVARCHAR) AS NRO_LINEA,
				CAST(Ltrim(Rtrim(Cod_Rapido))	AS NVARCHAR) AS COD_RAPIDO,
				CAST(Ltrim(Rtrim(Descripcion))	AS NVARCHAR) AS DESCRIPCION,
				CAST(Ltrim(Rtrim(Cantidad))		AS NVARCHAR) AS CANTIDAD,
				CAST(Ltrim(Rtrim(Cod_Unimed))	AS NVARCHAR) AS UNIDAD,
				CAST(Ltrim(Rtrim('CLP'))		AS NVARCHAR) AS TIPO_MONEDA,
				CAST(Ltrim(Rtrim(Total))		AS NVARCHAR) AS TOTAL
					FROM SAV_VT.DBO.SAV_VT_FCVDet WITH(NOLOCK)
						WHERE NRO_INTERNO = @NRO_INTERNO

		--HACEMOS SET A LA VARIABLE @ID_DOCUMENTO
		SET @ID_DOCUMENTO =(SELECT Id_Documento
								FROM SAV_VT.DBO.SAV_VT_FCVCab WITH(NOLOCK)
									WHERE Nro_Impreso = @NRO_IMPRESO)

		--INSERT A TABLA TEMPORAL #RESULT_THREE
		INSERT INTO #RESULT_THREE
			SELECT 
				CAST(Ltrim(Rtrim(Tipo_DocumentoPago))	AS NVARCHAR) AS TIPO_DOCUMENTO_PAGO,
				CAST(Ltrim(Rtrim(Monto))				AS NVARCHAR) AS MONTO 
					FROM SAV_CJ.DBO.SAV_CJ_ASIGNACION_TRANSACCION WITH(NOLOCK)
						WHERE Id_DocumentoPagar = @ID_DOCUMENTO

		--HACEMOS SET A LA VARIABLE @NRO_DOCUMENTO, @CHANNEL, @TIENDA, @NRO_CONTRATO
		SET @NRO_DOCUMENTO = (SELECT FECHA + TIENDA + CAJA + CORRELATIVO FROM #CODIGO_POR_DES)
		SET @CHANNEL = (SELECT CHANNEL FROM #CODIGO_POR_DES)
		SET @TIENDA = (SELECT TIENDA FROM #CODIGO_POR_DES)
		SET @NRO_CONTRATO = (SELECT NRO_CONTRATO FROM #CODIGO_POR_DES)

		--INSERT A TABLA TEMPORAL #RESULT_THREE
		INSERT INTO #RESULT_FOUR(ORDEN_VENTA, NRO_DOCUMENTO, CHANNEL, TIENDA, NRO_CONTRATO)
				SELECT
					CAST(Ltrim(Rtrim(@CODIGO_POR))	AS NVARCHAR),
					CAST(Ltrim(Rtrim(@NRO_DOCUMENTO)) AS NVARCHAR),
					CAST(Ltrim(Rtrim(@CHANNEL)) AS NVARCHAR),
					CAST(Ltrim(Rtrim(@TIENDA)) AS NVARCHAR),
					CAST(Ltrim(Rtrim(@NRO_CONTRATO)) AS NVARCHAR)
	END

	DROP TABLE #CODIGO_POR_DES	
	SELECT * FROM #RESULT_ONE
	DROP TABLE #RESULT_ONE
	SELECT * FROM #RESULT_TWO
	DROP TABLE #RESULT_TWO
	SELECT * FROM #RESULT_THREE
	DROP TABLE #RESULT_THREE
	SELECT * FROM #RESULT_FOUR
	DROP TABLE #RESULT_FOUR

	RETURN;
END;


