<%@ Language="VBScript" CodePage="1252" EnableSessionState="False" %>
<%
'++
' File generated by OBCOM Record Wizard 5.1.120
'
' Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
'
' All  rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
' used under the terms of its associated license document.  You  may  NOT  copy,
' modify,  sublicense,  or  distribute this source file or portions of it unless
' previously authorized in writing by OBCOM INGENIERIA S.A. In any  event,  this
' notice and above copyright must always be included verbatim with this file.
'
' File Name:       VALDCTO_OBTIENEDCTO_E.asp
' Creation Date:   23-Jul-2019 11:59:33
' Source Database: ECUBAS at APOLO\QACOLUMBIA, User:SavSysUser
' Library Name:    VALDCTO_LAYOUTS
' Record Name:     VALDCTO_OBTIENEDCTO_E
' Last Edition:    23-Jul-2019 11:49:36, IMPERIAL@IMPERIALXP
' Description:     Layout de Entrada para Validación de Desuentos por Convenio
'-+
' RUT:             Rut a Consultar
' NRO_INTERNO:     Nro Interno Vale
' ORIGEN:          Orignen Consulta
' COD_CONVENIO:    Codigo de convenio a aplicar
' APLICAR_CONVENIO: Si se aplica descuento al vale transitorio
'--
    Response.Expires = -1
    Response.CacheControl = "no-cache"
    Response.AddHeader "Pragma", "no-cache"
    Response.ContentType = "text/plain; charset=iso-8859-1"
%>
VR:1.0:VALDCTO_OBTIENEDCTO_E:2019-07-23:11:59:33
X:15:RUT
N:11:NRO_INTERNO
X:3:ORIGEN
X:3:COD_CONVENIO
N:1:APLICAR_CONVENIO
CS:33:VALDCTO_OBTIENEDCTO_E:BBDsCggDtTp1V2iqi29ouw
