<%@ Language="VBScript" CodePage="1252" EnableSessionState="False" %>
<%
'++
' File generated by OBCOM Record Wizard 5.1.120
'
' Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
'
' All  rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
' used under the terms of its associated license document.  You  may  NOT  copy,
' modify,  sublicense,  or  distribute this source file or portions of it unless
' previously authorized in writing by OBCOM INGENIERIA S.A. In any  event,  this
' notice and above copyright must always be included verbatim with this file.
'
' File Name:       WSAVISOIMPAGO_E.asp
' Creation Date:   23-jun-2013 03:37:06
' Source Database: ECUBAS at APOLO, User:SavSysUser
' Library Name:    WSAVISOIMPAGO
' Record Name:     WSAVISOIMPAGO_E
' Last Edition:    28-may-2013 00:25:51, DESARROLLO07@DESARROLLO07
' Description:     Entrada del aviso de facturas inpagas
'-+
' SRUTSR:          Rut Cliente
' SNOMBRESR:       Nombre Cliente
' SPAISSR:         Pais de origen
' NCANTDOCTOS:     Cantidad de documentos
' SNUMDOCTO:       Numeros de documentos
' SMONEDA:         Tipo de moneda
' NMONTO:          Monto Informado
' SFECEMISION:     Fecha de emision
' SFECVENCE:       Fecha de vencimiento
' SOBSERVACION:    Observacion
' NPOLIZA:         Numero de la poliza
'--
    Response.Expires = -1
    Response.CacheControl = "no-cache"
    Response.AddHeader "Pragma", "no-cache"
    Response.ContentType = "text/plain; charset=iso-8859-1"
%>
VR:1.0:WSAVISOIMPAGO_E:2013-06-23:03:37:06
X:15:SRUTSR
X:300:SNOMBRESR
X:200:SPAISSR
N:9:NCANTDOCTOS
X:500:SNUMDOCTO
X:100:SMONEDA
N:20:NMONTO
X:200:SFECEMISION
X:200:SFECVENCE
X:500:SOBSERVACION
N:10:NPOLIZA
CS:2054:WSAVISOIMPAGO_E:8DxzPugpgwCuQG1gj4aaFb
