<%@ Language="VBScript" CodePage="1252" EnableSessionState="False" %>
<%
'++
' File generated by OBCOM Record Wizard 5.1.120
'
' Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
'
' All  rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
' used under the terms of its associated license document.  You  may  NOT  copy,
' modify,  sublicense,  or  distribute this source file or portions of it unless
' previously authorized in writing by OBCOM INGENIERIA S.A. In any  event,  this
' notice and above copyright must always be included verbatim with this file.
'
' File Name:       WSCONSINN_E.asp
' Creation Date:   23-jun-2013 03:38:31
' Source Database: ECUBAS at APOLO, User:SavSysUser
' Library Name:    WSCONSINN
' Record Name:     WSCONSINN_E
' Last Edition:    28-may-2013 01:49:37, DESARROLLO07@DESARROLLO07
' Description:     Entrada Solicitud
'-+
' SRUTSR:          Rut cliente
' SNOMBRESR:       Nombre Cliente
' SDIRECCIONSR:    Direccion Cliente
' SCIUDADSR:       Ciudad Cliente
' SCODIGO:         Codigo cliente
'--
    Response.Expires = -1
    Response.CacheControl = "no-cache"
    Response.AddHeader "Pragma", "no-cache"
    Response.ContentType = "text/plain; charset=iso-8859-1"
%>
VR:1.0:WSCONSINN_E:2013-06-23:03:38:31
X:20:SRUTSR
X:300:SNOMBRESR
X:300:SDIRECCIONSR
X:200:SCIUDADSR
X:200:SCODIGO
X:200:SLOCAL
N:10:NPOLIZA
CS:1230:WSCONSINN_E:zLf8dKfJSPadhi4ND8TuUn
