<%@ Language="VBScript" CodePage="1252" EnableSessionState="False" %>
<%
'++
' File generated by OBCOM Record Wizard 5.1.120
'
' Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
'
' All  rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
' used under the terms of its associated license document.  You  may  NOT  copy,
' modify,  sublicense,  or  distribute this source file or portions of it unless
' previously authorized in writing by OBCOM INGENIERIA S.A. In any  event,  this
' notice and above copyright must always be included verbatim with this file.
'
' File Name:       WSESTSOLIC_E.asp
' Creation Date:   8-jul-2013 23:03:26
' Source Database: ECUBAS at APOLO, User:SavSysUser
' Library Name:    WSESTSOLIC
' Record Name:     WSESTSOLIC_E
' Last Edition:    23-jun-2013 03:39:55, DESARROLLO07@DESARROLLO07
' Description:     Parametros de entrada de la consulta
'--
    Response.Expires = -1
    Response.CacheControl = "no-cache"
    Response.AddHeader "Pragma", "no-cache"
    Response.ContentType = "text/plain; charset=iso-8859-1"
%>
VR:1.0:WSESTSOLIC_E:2013-07-08:23:03:26
X:30:NPOLIZA
CS:30:WSESTSOLIC_E:NQrQlEK0Sm8SsQJwwMAt0E
