<%@ Language="VBScript" CodePage="1252" EnableSessionState="False" %>
<%
'++
' File generated by OBCOM Record Wizard 5.1.120
'
' Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
'
' All  rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
' used under the terms of its associated license document.  You  may  NOT  copy,
' modify,  sublicense,  or  distribute this source file or portions of it unless
' previously authorized in writing by OBCOM INGENIERIA S.A. In any  event,  this
' notice and above copyright must always be included verbatim with this file.
'
' File Name:       WSINGRESASOLICITUD_E.asp
' Creation Date:   23-jun-2013 03:38:40
' Source Database: ECUBAS at APOLO, User:SavSysUser
' Library Name:    WSINGRESASOLICITUD
' Record Name:     WSINGRESASOLICITUD_E
' Last Edition:    29-may-2013 23:05:19, DESARROLLO07@DESARROLLO07
' Description:     Parametros de entrada de la solicitud
'--
    Response.Expires = -1
    Response.CacheControl = "no-cache"
    Response.AddHeader "Pragma", "no-cache"
    Response.ContentType = "text/plain; charset=iso-8859-1"
%>
VR:1.0:WSINGRESASOLICITUD_E:2013-06-23:03:38:40
X:50:STIPO
X:20:SRUTPAG
X:20:SRUTSR
X:50:STIPOPERSONA
X:200:SNOMBRESR
X:300:SDIRECCIONSR
X:200:SCIUDADSR
X:200:SPAISSR
X:100:SMONEDA
N:30:NMONTO
N:30:NLINNEG1
N:30:NLINNEG2
N:30:NLINNEG3
N:30:NLINNEG4
N:30:NLINNEG5
X:300:SOBSERVACION
N:10:NPOLIZA
CS:1630:WSINGRESASOLICITUD_E:cioS3jWHqVZytHWFO6AX5S
