<%@ Language="VBScript" CodePage="1252" EnableSessionState="False" %>
<%
'++
' File generated by OBCOM Record Wizard 5.1.120
'
' Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
'
' All  rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
' used under the terms of its associated license document.  You  may  NOT  copy,
' modify,  sublicense,  or  distribute this source file or portions of it unless
' previously authorized in writing by OBCOM INGENIERIA S.A. In any  event,  this
' notice and above copyright must always be included verbatim with this file.
'
' File Name:       WSSALDO_S.asp
' Creation Date:   23-jun-2013 03:39:14
' Source Database: ECUBAS at APOLO, User:SavSysUser
' Library Name:    WSSALDO
' Record Name:     WSSALDO_S
' Last Edition:    29-may-2013 23:20:33, DESARROLLO07@DESARROLLO07
' Description:     parametros de salida del servicio de consulta
'--
    Response.Expires = -1
    Response.CacheControl = "no-cache"
    Response.AddHeader "Pragma", "no-cache"
    Response.ContentType = "text/plain; charset=iso-8859-1"
%>
VR:1.0:WSSALDO_S:2013-06-23:03:39:14
X:8000:VRESPSERWEB
CS:8000:WSSALDO_S:taEa2BssKawaTGmKE30Ly8
