'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsSaldo
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsSaldoSoap", [Namespace]:="http://tempuri.org/wsSaldo/Service1")>  _
    Partial Public Class wsSaldo
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CallwsSaldoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SERVPOR.My.MySettings.Default.SRVPOL_wsSaldo_wsSaldo
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CallwsSaldoCompleted As CallwsSaldoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsSaldo/Service1/wsSaldo", RequestElementName:="wsSaldo", RequestNamespace:="http://tempuri.org/wsSaldo/Service1", ResponseElementName:="wsSaldoResponse", ResponseNamespace:="http://tempuri.org/wsSaldo/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallwsSaldo(ByVal nPoliza As Integer, ByVal sEmpresa As String, ByVal sUsuario As String, ByVal sContrasena As String, ByVal sRutSR As String, ByVal sNombreSR As String, ByVal nAnoMes As Integer) As <System.Xml.Serialization.XmlElementAttribute("wsSaldoResult")> clsLinea
            Dim results() As Object = Me.Invoke("CallwsSaldo", New Object() {nPoliza, sEmpresa, sUsuario, sContrasena, sRutSR, sNombreSR, nAnoMes})
            Return CType(results(0),clsLinea)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallwsSaldoAsync(ByVal nPoliza As Integer, ByVal sEmpresa As String, ByVal sUsuario As String, ByVal sContrasena As String, ByVal sRutSR As String, ByVal sNombreSR As String, ByVal nAnoMes As Integer)
            Me.CallwsSaldoAsync(nPoliza, sEmpresa, sUsuario, sContrasena, sRutSR, sNombreSR, nAnoMes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallwsSaldoAsync(ByVal nPoliza As Integer, ByVal sEmpresa As String, ByVal sUsuario As String, ByVal sContrasena As String, ByVal sRutSR As String, ByVal sNombreSR As String, ByVal nAnoMes As Integer, ByVal userState As Object)
            If (Me.CallwsSaldoOperationCompleted Is Nothing) Then
                Me.CallwsSaldoOperationCompleted = AddressOf Me.OnCallwsSaldoOperationCompleted
            End If
            Me.InvokeAsync("CallwsSaldo", New Object() {nPoliza, sEmpresa, sUsuario, sContrasena, sRutSR, sNombreSR, nAnoMes}, Me.CallwsSaldoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallwsSaldoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallwsSaldoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallwsSaldoCompleted(Me, New CallwsSaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsSaldo/Service1")>  _
    Partial Public Class clsLinea
        
        Private nPolizaField As Integer
        
        Private sUsuarioField As String
        
        Private sResultadoField As String
        
        Private dFechaConField As String
        
        Private cSujetoField As clsPersona
        
        Private sMonedaField As String
        
        Private nMontoField As Integer
        
        '''<remarks/>
        Public Property nPoliza() As Integer
            Get
                Return Me.nPolizaField
            End Get
            Set
                Me.nPolizaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sUsuario() As String
            Get
                Return Me.sUsuarioField
            End Get
            Set
                Me.sUsuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sResultado() As String
            Get
                Return Me.sResultadoField
            End Get
            Set
                Me.sResultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property dFechaCon() As String
            Get
                Return Me.dFechaConField
            End Get
            Set
                Me.dFechaConField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cSujeto() As clsPersona
            Get
                Return Me.cSujetoField
            End Get
            Set
                Me.cSujetoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sMoneda() As String
            Get
                Return Me.sMonedaField
            End Get
            Set
                Me.sMonedaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nMonto() As Integer
            Get
                Return Me.nMontoField
            End Get
            Set
                Me.nMontoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsSaldo/Service1")>  _
    Partial Public Class clsPersona
        
        Private nCodigoField As Integer
        
        Private nRutField As Integer
        
        Private sDvField As String
        
        Private sTipoPersonaField As String
        
        Private sNombreField As String
        
        Private sDireccionField As String
        
        Private sCiudadField As String
        
        Private sPaisField As String
        
        '''<remarks/>
        Public Property nCodigo() As Integer
            Get
                Return Me.nCodigoField
            End Get
            Set
                Me.nCodigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nRut() As Integer
            Get
                Return Me.nRutField
            End Get
            Set
                Me.nRutField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sDv() As String
            Get
                Return Me.sDvField
            End Get
            Set
                Me.sDvField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sTipoPersona() As String
            Get
                Return Me.sTipoPersonaField
            End Get
            Set
                Me.sTipoPersonaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sNombre() As String
            Get
                Return Me.sNombreField
            End Get
            Set
                Me.sNombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sDireccion() As String
            Get
                Return Me.sDireccionField
            End Get
            Set
                Me.sDireccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sCiudad() As String
            Get
                Return Me.sCiudadField
            End Get
            Set
                Me.sCiudadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sPais() As String
            Get
                Return Me.sPaisField
            End Get
            Set
                Me.sPaisField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub CallwsSaldoCompletedEventHandler(ByVal sender As Object, ByVal e As CallwsSaldoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallwsSaldoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsLinea
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsLinea)
            End Get
        End Property
    End Class
End Namespace
