CREATE TABLE `PRO_MAESTRO` (
`COD_PROVEEDOR` nVARCHAR(11) NOT NULL,
`COD_SUCURSAL` nVARCHAR(3) NOT NULL,
PRIMARY KEY (`COD_PROVEEDOR`) 
);
CREATE TABLE `EMPRESA_CONVENIO` (
`CODIGO_CONVENIO` nVARCHAR(3) NOT NULL,
`COD_PROVEEDOR` int(11) NOT NULL AUTO_INCREMENT,
`COD_SUCURSAL` nVARCHAR(3) NOT NULL,
`NOMBRE_CONVENIO` nVARCHAR(150) NOT NULL,
`ESTADO` nVARCHAR(50) NOT NULL,
`FECHA_REGISTRO` datetime(8) NOT NULL ON UPDATE CURRENT_TIMESTAMP(8),
`FECHA_CONVENIO` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
`USUARIO_REGISTRO` nVARCHAR(150) NOT NULL,
PRIMARY KEY (`CODIGO_CONVENIO`) 
);
CREATE TABLE `CUPON_CONVENIO` (
`CODIGO_IMPRESO` nVARCHAR(11) NOT NULL,
`CODIGO_CONVENIO` nVARCHAR(3) NOT NULL,
`CORRELATIVO_CUPON` int NOT NULL AUTO_INCREMENT,
`COD_ORI_VTA` nVARCHAR(3) NOT NULL,
`FECHA_REGISTRO` datetime(8) NOT NULL ON UPDATE CURRENT_TIMESTAMP(8),
`FECHA_VIGENCIA` datetime(8) NOT NULL ON UPDATE CURRENT_TIMESTAMP(8),
`FECHA_UTILIZADO` datetime(8) NULL ON UPDATE CURRENT_TIMESTAMP(8),
`ACTIVO` nVARCHAR(1) NOT NULL,
`USUARIO_CREA` nVARCHAR(150) NOT NULL,
`VALOR_DESCUENTO` decimal NOT NULL,
`TIPO_DESCUENTO` int NOT NULL,
`PORCENTAJE` bit NOT NULL,
PRIMARY KEY (`CODIGO_IMPRESO`) 
);
CREATE TABLE `HISTORIAL` (
`ID_HISTORIAL` int(11) NOT NULL AUTO_INCREMENT,
`CODIGO_IMPRESO` int(11) NOT NULL,
`OBSERVACION` nVARCHAR(200) NOT NULL,
`FECHA_REGISTRO` datetime(8) NOT NULL ON UPDATE CURRENT_TIMESTAMP(8),
`ORIGEN` nVARCHAR(150) NOT NULL,
PRIMARY KEY (`ID_HISTORIAL`) 
);
CREATE TABLE `CONVENIO` (
`ID_CONVENIO` int(11) NOT NULL AUTO_INCREMENT,
`COD_TIPO` nVARCHAR(3) NOT NULL,
`DESCRIPCION` nVARCHAR(150) NOT NULL,
`VALOR` int(11) NOT NULL,
`USUARIO_CREA` nVARCHAR(150) NOT NULL,
`FECHA_REGISTRO` datetime(8) NOT NULL ON UPDATE CURRENT_TIMESTAMP(8),
PRIMARY KEY (`ID_CONVENIO`) 
);
CREATE TABLE `TIPO_DESCUENTO` (
`ID_TIPO_DESCUENTO` int NOT NULL AUTO_INCREMENT,
`PORCENTAJE` bit NOT NULL,
PRIMARY KEY (`ID_TIPO_DESCUENTO`) 
);

ALTER TABLE `EMPRESA_CONVENIO` ADD CONSTRAINT `fk_EMPRESA_CONVENIO_CONVENIO_1` FOREIGN KEY (`CODIGO_CONVENIO`) REFERENCES `CONVENIO` (`ID_CONVENIO`);
ALTER TABLE `CONVENIO` ADD CONSTRAINT `fk_CONVENIO_COPON_CONVENIO_1` FOREIGN KEY (`ID_CONVENIO`) REFERENCES `CUPON_CONVENIO` (`CODIGO_CONVENIO`);
ALTER TABLE `EMPRESA_CONVENIO` ADD CONSTRAINT `fk_EMPRESA_CONVENIO_COPON_CONVENIO_1` FOREIGN KEY (`CODIGO_CONVENIO`) REFERENCES `CUPON_CONVENIO` (`CODIGO_CONVENIO`);
ALTER TABLE `TIPO_DESCUENTO` ADD CONSTRAINT `fk_TIPO_DESCUENTO_COPON_CONVENIO_1` FOREIGN KEY (`ID_TIPO_DESCUENTO`) REFERENCES `CUPON_CONVENIO` (`VALOR_DESCUENTO`);
ALTER TABLE `PRO_MAESTRO` ADD CONSTRAINT `fk_PRO_MAESTRO_EMPRESA_CONVENIO_1` FOREIGN KEY (`COD_PROVEEDOR`) REFERENCES `EMPRESA_CONVENIO` (`COD_PROVEEDOR`);
ALTER TABLE `CUPON_CONVENIO` ADD CONSTRAINT `fk_CUPON_CONVENIO_HISTORIAL_1` FOREIGN KEY (`CODIGO_IMPRESO`) REFERENCES `HISTORIAL` (`CODIGO_IMPRESO`);

CREATE 
VIEW `view_1` AS 
;
