
		   CREATE TABLE #TempTapacantos (
					SKU_TABLERO		INT, 
					SKU_TAPACANTOS	INT, 
					DESCRIPCION		NVARCHAR(200),
					IMAGEN			NVARCHAR(200),
					CONTENIDO		NVARCHAR(100),
					ESPESOR			NVARCHAR(100),
					MATERIAL		NVARCHAR(100),
					LARGO			NVARCHAR(100)) 

			INSERT INTO #TempTapacantos
			SELECT a.COD_RAPIDO AS SKU_TABLERO,	
				   COD_ASOCIADO AS SKU_TAPACANTOS,	 
				   db.DESC_LARGA AS DESCRIPCION,
			ISNULL(a.image_url + CONVERT(NVARCHAR(13),a.COD_ASOCIADO) + '.jpg','') AS IMAGEN,
			0,
			0,
			0,
			0
			FROM SAV.dbo.SAV_Tapacantos_Asociados a
			INNER JOIN SAV.dbo.PRD_DATOSBASICOS  db WITH(NoLock) ON a.COD_ASOCIADO = db.COD_RAPIDO
			WHERE a.COD_RAPIDO = 70057


			UPDATE
				#TempTapacantos
			SET
				#TempTapacantos.LARGO = (SELECT CAST(dbo.fnSoloNumeros(CASE WHEN LEN(ISNULL(Detalle,0)) = 0 THEN '0' ELSE ISNULL(Detalle,0) END) AS INT) AS Detalle 
				FROM sav.dbo.PRD_FICHATECNICA 
				WHERE COD_DATOTECNICO = 4 
					AND COD_PRODUCTO = (SELECT COD_PRODUCTO FROM SAV.dbo.PRD_DATOSBASICOS WHERE COD_RAPIDO = #TempTapacantos.SKU_TAPACANTOS)) ,

				#TempTapacantos.CONTENIDO = (SELECT CAST(dbo.fnSoloNumeros(CASE WHEN LEN(ISNULL(Detalle,0)) = 0 THEN '0' ELSE ISNULL(Detalle,0) END) AS INT) AS Detalle 
				FROM sav.dbo.PRD_FICHATECNICA 
				WHERE COD_DATOTECNICO = 192 
					AND COD_PRODUCTO = (SELECT COD_PRODUCTO FROM SAV.dbo.PRD_DATOSBASICOS WHERE COD_RAPIDO = #TempTapacantos.SKU_TAPACANTOS)) ,

				#TempTapacantos.MATERIAL = (SELECT Detalle 
				FROM sav.dbo.PRD_FICHATECNICA 
				WHERE COD_DATOTECNICO = 30
					AND COD_PRODUCTO = (SELECT COD_PRODUCTO FROM SAV.dbo.PRD_DATOSBASICOS WHERE COD_RAPIDO = #TempTapacantos.SKU_TAPACANTOS)) ,

				#TempTapacantos.ESPESOR = (SELECT Detalle 
				FROM sav.dbo.PRD_FICHATECNICA 
				WHERE COD_DATOTECNICO = 5 
					AND COD_PRODUCTO = (SELECT COD_PRODUCTO FROM SAV.dbo.PRD_DATOSBASICOS WHERE COD_RAPIDO = #TempTapacantos.SKU_TAPACANTOS)) 

			SELECT 
				SKU_TABLERO,	
				SKU_TAPACANTOS, 
				DESCRIPCION,
				IMAGEN,
				CAST(dbo.fnSoloNumeros(CASE WHEN LEN(ISNULL(LARGO,0)) = 0 THEN  ISNULL(CONTENIDO,0) ELSE ISNULL(LARGO,0) END) AS INT) AS METROS,
				CAST(dbo.fnSoloNumeros(CASE WHEN LEN(ISNULL(ESPESOR,0)) = 0 THEN '0' ELSE ISNULL(ESPESOR,0) END) AS INT) AS ESPESOR,
				CASE WHEN LEN(ISNULL(MATERIAL,0)) = 0 THEN '0' ELSE ISNULL(MATERIAL,0) END AS MATERIAL  	
			 FROM #TempTapacantos
			 DROP TABLE #TempTapacantos