--SELECT * FROM sys.schemas WHERE principal_id=1

--SELECT  P.NOMPRODUCTO 'PRODUCTO',    C.NOMBRECATEGORIA 'CATEGORIA' 
--FROM PRODUCTOS P  
--	JOIN CATEGORIA C ON P.IDCATEGORIA = C.IDCATEGORIA  
--WHERE P.PRECIOUNIDAD BETWEEN 27 AND 30 ORDER BY P.NOMPRODUCTO

