SELECT * FROM EMPLEADOS

SELECT NOMBRE FROM PERSONAS
WHERE ALTA='S' OR (RUBIA='S' AND GAFAS='S')

SELECT NOMBRE,APELLIDOS FROM EMPLEADOS 
WHERE SEXO='M' AND SALARIO > 1300

SELECT NOMBRE FROM PERSONAS 
WHERE GAFAS='S' AND NOT ALTA='S' AND NOT RUBIA='S'

SELECT SUM(SALARIO) AS SUMA_SUELDO FROM EMPLEADOS

SELECT SUM(SALARIO), COUNT(*) FROM EMPLEADOS

SELECT SUM(SALARIO)/COUNT(*) AS MEDIA_SALARIO FROM EMPLEADOS

SELECT AVG(SALARIO) AS MEDIA_SALARIOS FROM EMPLEADOS

SELECT NOMBRE, APELLIDOS, SALARIO / 5525.5 * 100 AS PORCENTAJE FROM EMPLEADOS

SELECT AVG(SALARIO) AS SALARIO_MEDIO_HOMBRES FROM EMPLEADOS WHERE SEXO='H'

SELECT MAX(SALARIO) AS SALARIO_MAX, MIN(SALARIO) AS SALARIO_MIN FROM EMPLEADOS

SELECT SUM(SALARIO) AS PAGO_TOTAL_M FROM EMPLEADOS WHERE SEXO='M'

SELECT SEXO, COUNT(*)  AS EMPLEADOS FROM EMPLEADOS GROUP BY SEXO

SELECT DISTINCT SEXO FROM EMPLEADOS

SELECT SEXO,AVG(SALARIO)AS SALARIO_MEDIO, MAX(SALARIO) AS SALARIO_MAX, MIN(SALARIO) AS SALARIO_MIN FROM EMPLEADOS GROUP BY SEXO

SELECT NOMBRE,APELLIDOS,SALARIO FROM EMPLEADOS ORDER BY SALARIO

SELECT NOMBRE,APELLIDOS,SALARIO FROM EMPLEADOS ORDER BY SALARIO DESC

SELECT * FROM VEHICULOS WHERE ULTI_ITV BETWEEN '20080101' AND '20081231'

SELECT * FROM VEHICULOS WHERE not (ULTI_ITV BETWEEN '20080101' AND '20081231')

SELECT * FROM VEHICULOS WHERE not (ULTI_ITV BETWEEN '20080101' AND '20081231') OR ULTI_ITV IS NULL

select * from EMPLEADOS

select count(*) , count(ID_VEHICLO) , count(ULTI_ITV) from VEHICULOS

EXEC sp_help 'VEHICULOS'

SELECT * FROM EMPLEADOS WHERE APELLIDOS LIKE '%CALVO%'

select * from VEHICULOS where PROX_ITV between '20110101' and '20111231' and ULTI_ITV is null

INSERT INTO CAMISAS (CAMISA,PESO_GR) 
VALUES ('Lino Blanco','210'),
	   ('Algodon Naranja','290'),
	   ('Seda Negra','260');

select * from calzados 

SELECT * FROM CAMISAS,PANTALONES,CALZADOS

select camisa,pantalon from camisas,pantalones

SELECT CAMISA,PANTALON,CAMISAS.PESO_GR + PANTALONES.PESO_GR AS PESO_MUDA FROM CAMISAS,PANTALONES

SELECT C.CAMISA,P.PANTALON,Z.CALZADO,C.PESO_GR + P.PESO_GR + Z.PESO_GR AS PESO_MUDA FROM CAMISAS C, PANTALONES P, CALZADOS Z ORDER BY C.ID_CAMISA,P.ID_PANTALONES,Z.ID_CALZADO

SELECT CONCAT(' Camisa de ', C.CAMISA , ' Con Pantalon de ', P.PANTALON,' y ', Z.CALZADO) AS MUDA,C.PESO_GR + P.PESO_GR + Z.PESO_GR PESO_MUDA FROM CAMISAS C, PANTALONES P, CALZADOS Z ORDER BY C.ID_CAMISA, P.ID_PANTALONES, Z.CALZADO

SELECT CONCAT(' Pantalon de ', P.PANTALON, ' Con Calzado ', Z.CALZADO) AS MUDA FROM PANTALONES P, CALZADOS Z


---- Select a la tabla CAMISAS para mostrarlo tipo STRING 
  select concat('Camisa de ',CAMISA) as PRENDA
     from CAMISAS
	union all  --Une dos consultas a la ves Obsérvese como para realizar la operación de unión, es necesario que ambas devuelvan el mismo número de columnas, de lo contrario la consulta SQL es en conjunto errónea y SGBD no sabrá resolverla.
		select concat('Pantalón de ',PANTALON)
			from PANTALONES

	 --Peso medio de todas las mudas confeccionables entre camisas y pantalones:
select avg( C.PESO_GR + P.PESO_GR) PESO_MEDIO_MUDAS
  from CAMISAS C , PANTALONES P

  --Peso medio de todas las mudas confeccionables entre camisas, pantalones y calzados.
select avg( C.PESO_GR + P.PESO_GR + Z.PESO_GR) PESO_MEDIO_MUDAS
  from CAMISAS C , PANTALONES P , CALZADOS Z

  --Peso medio de todas las mudas confeccionables entre camisas y pantalones agrupado por camisa:
  select C.CAMISA , avg( C.PESO_GR + P.PESO_GR) PESO_MEDIO_MUDAS
    from CAMISAS C , PANTALONES P
group by C.CAMISA

--Peso medio de todas las mudas confeccionables entre camisas y pantalones agrupado por camisa con peso superior a 850 gramos:
  select C.CAMISA , avg( C.PESO_GR + P.PESO_GR) PESO_MEDIO_MUDAS
    from CAMISAS C , PANTALONES P
group by C.CAMISA
having avg( C.PESO_GR + P.PESO_GR) > 850

----Select de la felacion de ID distintos 
select *
  from CAMISAS C , PANTALONES P
 where C.ID_CAMISA != P.ID_PANTALONES

 --Union de tres select distintos para consultar tres tablas distintas 
    select concat('Camisa de ',CAMISA) as PRENDA
     from CAMISAS
union all
   select concat('Pantalón de ',PANTALON)
     from PANTALONES
union all
   select concat('Calzado: ',CALZADO)
     from CALZADOS

	 SELECT * FROM CURSOS C, PROFESORES P WHERE C.ID_PROFE = P.ID_PROFE

	 select concat('Curso de ',C.TITULO,', impartido por ',P.NOMBRE,' ',P.APELLIDO) CURSOS
  from CURSOS C, PROFESORES P 
 where C.ID_PROFE = P.ID_PROFE

 SELECT * FROM ALUMNOS_CURSOS AC, ALUMNOS A, CURSOS C WHERE AC.ID_ALUMNO = A.ID_ALUMNO AND AC.ID_ALUMNO = C.ID_CURSO

 select *
  from ALUMNOS_CURSOS AC, ALUMNOS A, CURSOS C
 where AC.ID_ALUMNO = A.ID_ALUMNO
   and AC.ID_CURSO  = C.ID_CURSO


     select C.TITULO CURSO , concat(A.APELLIDO,', ',A.NOMBRE ) ALUMNO
    from ALUMNOS_CURSOS AC, ALUMNOS A, CURSOS C
   where AC.ID_ALUMNO = A.ID_ALUMNO
     and AC.ID_CURSO  = C.ID_CURSO
order by C.TITULO , A.NOMBRE , A.APELLIDO


SELECT C.TITULO CURSO
FROM ALUMNOS_CURSOS AC, CURSOS C
WHERE AC.ID_CURSO = C.ID_CURSO AND AC.ID_ALUMNO = 1


