SELECT * FROM MASCOTAS

--INSERT INTO MASCOTAS (NOMBRE,ESPECIE,SEXO,UBICACION,ESTADO)
--VALUES ('Budy','P','M','E05','B'),('Pipo','P','M','E02','B'),('Nuna','P','H','E02','A'),('Brust','P','M','E03','A'),('Americo','G','M','E04','A'),('Sombra','P','H','E05','A'),('Amaya','G','H','E04','A'),('Talia','G','H','E01','B'),('Trabis','P','M','E02','A'),('Tesa','G','H','E01','A'),('Titito','G','M','E04','B'),('Truca','P','H','E02','A'),('Zulai','P','M','E05','A'),('Dandi','G','M','E04','A'),('Ras','G','M','E01','A'),('Canela','P','H','E02','A');

--SELECT SEXO,COUNT(*) AS PERROS_VIGENTES FROM MASCOTAS 
--WHERE ESPECIE='P' AND ESTADO='A'
--GROUP BY SEXO

--INSERT INTO VEHICULOS 
--	(MARCA,MODELO,PROX_ITV)
--VALUES ('Alfa Romero','Brera','2011-10-20'),
	   --('BMW','X3','2010-07-18'),
	   --('Ford','Fiesta','2010-04-22');

INSERT INTO VEHICULOS 
	(MARCA,MODELO,PROX_ITV,ULTI_ITV)
VALUES 	   ('Seat','Panda','2019-12-01','2008-12-01'),
	   ('Citroen','C2','2010-08-24','2009-08-24');

SELECT UBICACION,COUNT(*) AS EJEMPLARES FROM MASCOTAS
WHERE ESTADO='A'
GROUP BY UBICACION

SELECT ESPECIE,SEXO,COUNT(*) AS EJEMPLARES_VIGENTES FROM MASCOTAS
WHERE ESTADO='A'
GROUP BY ESPECIE,SEXO

SELECT UBICACION,ESPECIE,SEXO,COUNT(*) AS EJEMPLARES_VIGENTES FROM MASCOTAS
WHERE ESTADO='A'
GROUP BY UBICACION,ESPECIE,SEXO

SELECT ESPECIE,COUNT(*) AS BAJAS FROM MASCOTAS
WHERE ESTADO='B'
GROUP BY ESPECIE

SELECT UBICACION,COUNT(*) AS PERROS_MACHOS FROM MASCOTAS
WHERE SEXO='M' AND ESPECIE='P' AND ESTADO='A'
GROUP BY UBICACION

SELECT DISTINCT UBICACION,ESPECIE FROM MASCOTAS WHERE ESTADO='A'

SELECT UBICACION,COUNT(*) AS EJEMPLARES FROM MASCOTAS WHERE ESTADO='A' GROUP BY UBICACION HAVING COUNT(*) > 2

SELECT UBICACION,COUNT(*) AS EJEMPLARES FROM MASCOTAS WHERE ESTADO='A' AND (UBICACION='E02' OR UBICACION='E03') GROUP BY UBICACION

 select UBICACION , count(*) as EJEMPLARES from MASCOTAS where ESTADO = 'A' group by UBICACION having UBICACION = 'E02'  or UBICACION = 'E03' 

SELECT UBICACION,COUNT(*) AS EJEMPLARES FROM MASCOTAS WHERE ESTADO='A' GROUP BY UBICACION HAVING COUNT(*)=1

SELECT UBICACION AS UBICACION_CON_UN_EJEMPLAR FROM MASCOTAS WHERE ESTADO='A' GROUP BY UBICACION HAVING COUNT(*)=1

SELECT UBICACIOIN,COUNT(*) AS EJEMPLARES FROM MASCOTAS WHERE ESTADO='A' GROUP BY UBICACION HAVING COUNT(*) BETWEEN 2 AND 3 

select * from vehiculos WHERE ULTI_ITV IS NULL

select * from vehiculos where ulti_itv is not null

SELECT DISTINCT SEXO FROM EMPLEADOS

SELECT UBICACION,COUNT(*) AS EJEMPLARES FROM MASCOTAS WHERE ESTADO='A' GROUP BY UBICACION HAVING COUNT(*) BETWEEN 2 AND 3

SELECT NOMBRE,APELLIDOS,SALARIO FROM EMPLEADOS ORDER BY SALARIO

SELECT NOMBRE,APELLIDOS,SALARIO FROM EMPLEADOS ORDER BY SALARIO DESC

SELECT * FROM MASCOTAS WHERE ESPECIE='P' ORDER BY ESTADO DESC,NOMBRE ASC

SELECT * FROM PERSONAS ORDER BY RUBIA DESC, ALTA DESC,GAFAS

 select UBICACION, count(*) as EJEMPLARES from MASCOTAS
   where ESTADO = 'A'
group by UBICACION
  having count(*) > 1
order by count(*) desc, UBICACION

SELECT * FROM EMPLEADOS WHERE APELLIDOS LIKE'R%'

SELECT * FROM EMPLEADOS WHERE APELLIDOS LIKE'%N'

SELECT * FROM EMPLEADOS WHERE APELLIDOS LIKE'%AR%'