'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsEstSolic
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsEstSolicSoap", [Namespace]:="http://tempuri.org/wsEstSolic/Service1")>  _
    Partial Public Class wsEstSolic
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CallwsEstSolicOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SERVPOR.My.MySettings.Default.SRVPOL_wsEstSolic_wsEstSolic
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CallwsEstSolicCompleted As CallwsEstSolicCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsEstSolic/Service1/wsEstSolic", RequestElementName:="wsEstSolic", RequestNamespace:="http://tempuri.org/wsEstSolic/Service1", ResponseElementName:="wsEstSolicResponse", ResponseNamespace:="http://tempuri.org/wsEstSolic/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallwsEstSolic(ByVal nPoliza As Integer, ByVal sEmpresa As String, ByVal sUsuario As String, ByVal sContrasena As String) As <System.Xml.Serialization.XmlElementAttribute("wsEstSolicResult")> clsLinea
            Dim results() As Object = Me.Invoke("CallwsEstSolic", New Object() {nPoliza, sEmpresa, sUsuario, sContrasena})
            Return CType(results(0),clsLinea)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallwsEstSolicAsync(ByVal nPoliza As Integer, ByVal sEmpresa As String, ByVal sUsuario As String, ByVal sContrasena As String)
            Me.CallwsEstSolicAsync(nPoliza, sEmpresa, sUsuario, sContrasena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallwsEstSolicAsync(ByVal nPoliza As Integer, ByVal sEmpresa As String, ByVal sUsuario As String, ByVal sContrasena As String, ByVal userState As Object)
            If (Me.CallwsEstSolicOperationCompleted Is Nothing) Then
                Me.CallwsEstSolicOperationCompleted = AddressOf Me.OnCallwsEstSolicOperationCompleted
            End If
            Me.InvokeAsync("CallwsEstSolic", New Object() {nPoliza, sEmpresa, sUsuario, sContrasena}, Me.CallwsEstSolicOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallwsEstSolicOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallwsEstSolicCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallwsEstSolicCompleted(Me, New CallwsEstSolicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsEstSolic/Service1")>  _
    Partial Public Class clsLinea
        
        Private nPolizaField As Integer
        
        Private sUsuarioField As String
        
        Private sResultadoField As String
        
        Private dFechaConField As String
        
        Private cLineaNomCollectionField() As clsLineaNom
        
        '''<remarks/>
        Public Property nPoliza() As Integer
            Get
                Return Me.nPolizaField
            End Get
            Set
                Me.nPolizaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sUsuario() As String
            Get
                Return Me.sUsuarioField
            End Get
            Set
                Me.sUsuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sResultado() As String
            Get
                Return Me.sResultadoField
            End Get
            Set
                Me.sResultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property dFechaCon() As String
            Get
                Return Me.dFechaConField
            End Get
            Set
                Me.dFechaConField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cLineaNomCollection() As clsLineaNom()
            Get
                Return Me.cLineaNomCollectionField
            End Get
            Set
                Me.cLineaNomCollectionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsEstSolic/Service1")>  _
    Partial Public Class clsLineaNom
        
        Private nRutSRField As Integer
        
        Private sDvSRField As String
        
        Private sNombreSRField As String
        
        Private sMonedaField As String
        
        Private nMontoSolicField As Integer
        
        Private nMontoAprobField As Integer
        
        Private sEstadoField As String
        
        '''<remarks/>
        Public Property nRutSR() As Integer
            Get
                Return Me.nRutSRField
            End Get
            Set
                Me.nRutSRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sDvSR() As String
            Get
                Return Me.sDvSRField
            End Get
            Set
                Me.sDvSRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sNombreSR() As String
            Get
                Return Me.sNombreSRField
            End Get
            Set
                Me.sNombreSRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sMoneda() As String
            Get
                Return Me.sMonedaField
            End Get
            Set
                Me.sMonedaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nMontoSolic() As Integer
            Get
                Return Me.nMontoSolicField
            End Get
            Set
                Me.nMontoSolicField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nMontoAprob() As Integer
            Get
                Return Me.nMontoAprobField
            End Get
            Set
                Me.nMontoAprobField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property sEstado() As String
            Get
                Return Me.sEstadoField
            End Get
            Set
                Me.sEstadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub CallwsEstSolicCompletedEventHandler(ByVal sender As Object, ByVal e As CallwsEstSolicCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallwsEstSolicCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsLinea
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsLinea)
            End Get
        End Property
    End Class
End Namespace
